name: Classroom Autograding

on:
  push:
    branches:
      - main

jobs:
  autograding:
    uses: cbfacademy/autograding-workflows/.github/workflows/classroom-autograding.yml@main
    secrets:
      CLASSROOM_TOKEN: ${{ secrets.CLASSROOM_TOKEN }}
